;;; perspective-project-bridge-test.el --- Tests for perspective-project-bridge -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:

;; ERT tests for perspective-project-bridge.

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'project)

(unless (require 'perspective nil t)
  (defvar persp-mode t)
  (defmacro with-perspective (_name &rest body)
    `(progn ,@body))
  (defun persp-new (name)
    (list :name name))
  (defun persp-name (persp)
    (plist-get persp :name))
  (defun persp-add-buffer (&rest _args))
  (defun persp-curr ())
  (defun persp-remove-buffer (&rest _args))
  (defun persp-switch (&rest _args))
  (defun persp-switch-to-buffer (&rest _args))
  (defun persp-make-variable-persp-local (&rest _args))
  (defun persp-kill (&rest _args))
  (defun persp-names ()
    nil)
  (provide 'perspective))

(load-file (expand-file-name "../perspective-project-bridge.el"
                             (file-name-directory
                              (or load-file-name buffer-file-name))))

(ert-deftest perspective-project-bridge-find-perspective-for-buffer-skips-nil-root ()
  "Return nil without creating a perspective when project root is nil."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-persp nil))
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   nil))
                ((symbol-function 'persp-new)
                 (lambda (&rest _args)
                   (ert-fail "persp-new should not be called when project root is nil"))))
        (should-not
         (perspective-project-bridge-find-perspective-for-buffer (current-buffer)))))))

(ert-deftest perspective-project-bridge-find-perspective-for-buffer-creates-perspective ()
  "Create and return a perspective when project root exists."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-persp nil)
        (added-buffer nil))
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'persp-new)
                 (lambda (name)
                   (list :name name)))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'persp-add-buffer)
                 (lambda (buffer)
                   (setq added-buffer buffer))))
        (let ((persp (perspective-project-bridge-find-perspective-for-buffer
                      (current-buffer))))
          (should (equal (plist-get persp :name) "sample-project"))
          (should (eq added-buffer (current-buffer)))
          (should perspective-project-bridge-persp))))))

(ert-deftest perspective-project-bridge-find-file-advice-switches-after-confirmation ()
  "Switch to project perspective for interactive find-file when confirmed."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-confirm-on-interactive-find-file t)
        (switched-name nil)
        (prompt-count 0)
        (orig-saw-switch nil))
    (with-temp-buffer
      (cl-letf (((symbol-function 'called-interactively-p)
                 (lambda (&rest _args)
                   t))
                ((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (setq prompt-count (1+ prompt-count))
                   t))
                ((symbol-function 'persp-new)
                 (lambda (name)
                   (list :name name)))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'persp-add-buffer)
                 (lambda (&rest _args)))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   'other-persp))
                ((symbol-function 'persp-remove-buffer)
                 (lambda (&rest _args)))
                ((symbol-function 'persp-switch)
                 (lambda (name)
                   (setq switched-name name)))
                ((symbol-function 'persp-switch-to-buffer)
                 (lambda (&rest _args))))
        (perspective-project-bridge-find-file-advice
         (lambda (&rest _args)
           (setq orig-saw-switch (equal switched-name "sample-project"))
           (current-buffer))
         "src/file.el")
        (should (= prompt-count 1))
        (should (equal switched-name "sample-project"))
        (should orig-saw-switch)))))

(ert-deftest perspective-project-bridge-find-file-advice-skips-prompt-when-already-in-project-perspective ()
  "Skip prompt when current perspective already matches target project."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-confirm-on-interactive-find-file t)
        (prompt-count 0)
        (switch-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'called-interactively-p)
                 (lambda (&rest _args)
                   t))
                ((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (setq prompt-count (1+ prompt-count))
                   t))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   (list :name "sample-project")))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (perspective-project-bridge-find-file-advice
         (lambda (&rest _args)
           (current-buffer))
         "src/file.el")
        (should (= prompt-count 0))
        (should (= switch-count 0))))))

(ert-deftest perspective-project-bridge-find-file-advice-keeps-current-when-declined ()
  "Do not switch perspectives when prompt is declined."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-confirm-on-interactive-find-file t)
        (switch-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'called-interactively-p)
                 (lambda (&rest _args)
                   t))
                ((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   nil))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (perspective-project-bridge-find-file-advice
         (lambda (&rest _args)
           (current-buffer))
         "src/file.el")
        (should (= switch-count 0))))))

(ert-deftest perspective-project-bridge-find-file-advice-skips-for-noninteractive-calls ()
  "Skip prompt and switching for non-interactive find-file calls."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-confirm-on-interactive-find-file t)
        (switch-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'called-interactively-p)
                 (lambda (&rest _args)
                   nil))
                ((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (ert-fail "Prompt should not be shown for non-interactive calls")))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (perspective-project-bridge-find-file-advice
         (lambda (&rest _args)
           (current-buffer))
         "src/file.el")
        (should (= switch-count 0))))))

(ert-deftest perspective-project-bridge-find-file-advice-skips-when-project-root-missing ()
  "Skip prompt and switch when file has no project root."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-confirm-on-interactive-find-file t)
        (switch-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'called-interactively-p)
                 (lambda (&rest _args)
                   t))
                ((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   nil))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (ert-fail "Prompt should not be shown when project root is missing")))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (perspective-project-bridge-find-file-advice
         (lambda (&rest _args)
           (current-buffer))
         "src/file.el")
        (should (= switch-count 0))))))

(ert-deftest perspective-project-bridge-find-file-advice-respects-reentry-guard ()
  "Bypass prompt and switching when already inside find-file advice."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-confirm-on-interactive-find-file t)
        (perspective-project-bridge--in-find-file-advice t)
        (orig-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'called-interactively-p)
                 (lambda (&rest _args)
                   t))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (ert-fail "Prompt should not run while reentry guard is active"))))
        (perspective-project-bridge-find-file-advice
         (lambda (&rest _args)
           (setq orig-count (1+ orig-count))
           (current-buffer))
         "src/file.el")
        (should (= orig-count 1))))))

(ert-deftest perspective-project-bridge-consult-file-action-advice-switches-after-confirmation ()
  "Switch to project perspective for consult file actions when confirmed."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-consult-prompt-on-file-action t)
        (switched-name nil)
        (prompt-count 0)
        (orig-saw-switch nil))
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (setq prompt-count (1+ prompt-count))
                   t))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   (list :name "other-project")))
                ((symbol-function 'persp-new)
                 (lambda (name)
                   (list :name name)))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'persp-switch)
                 (lambda (name)
                   (setq switched-name name))))
        (perspective-project-bridge-consult-file-action-advice
         (lambda (&rest _args)
           (setq orig-saw-switch (equal switched-name "sample-project"))
           'ok)
         "src/file.el")
        (should (= prompt-count 1))
        (should (equal switched-name "sample-project"))
        (should orig-saw-switch)))))

(ert-deftest perspective-project-bridge-consult-file-action-advice-keeps-current-when-declined ()
  "Do not switch perspectives for consult file actions when prompt is declined."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-consult-prompt-on-file-action t)
        (prompt-count 0)
        (switch-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (setq prompt-count (1+ prompt-count))
                   nil))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   (list :name "other-project")))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (perspective-project-bridge-consult-file-action-advice
         (lambda (&rest _args)
           'ok)
         "src/file.el")
        (should (= prompt-count 1))
        (should (= switch-count 0))))))

(ert-deftest perspective-project-bridge-consult-file-action-advice-skips-when-already-in-target ()
  "Do not prompt for consult file actions when already in target perspective."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-consult-prompt-on-file-action t)
        (prompt-count 0)
        (switch-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   (list :name "sample-project")))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (setq prompt-count (1+ prompt-count))
                   t))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (perspective-project-bridge-consult-file-action-advice
         (lambda (&rest _args)
           'ok)
         "src/file.el")
        (should (= prompt-count 0))
        (should (= switch-count 0))))))

(ert-deftest perspective-project-bridge-consult-file-action-advice-skips-when-root-missing ()
  "Do not prompt for consult file actions when project root is unavailable."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-consult-prompt-on-file-action t))
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   nil))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (ert-fail "Prompt should not run when project root is unavailable"))))
        (perspective-project-bridge-consult-file-action-advice
         (lambda (&rest _args)
           'ok)
         "src/file.el")))))

(provide 'perspective-project-bridge-test)

;;; perspective-project-bridge-test.el ends here
