;;; perspective-project-bridge-test.el --- Tests for perspective-project-bridge -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:

;; ERT tests for perspective-project-bridge.

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'project)

(unless (require 'perspective nil t)
  (defvar persp-mode t)
  (defvar persp-initial-frame-name "main")
  (defmacro with-perspective (_name &rest body)
    `(progn ,@body))
  (defun persp-new (name)
    (list :name name))
  (defun persp-name (persp)
    (plist-get persp :name))
  (defun persp-add-buffer (&rest _args))
  (defun persp-curr ())
  (defun persp-remove-buffer (&rest _args))
  (defun persp-switch (&rest _args))
  (defun persp-switch-to-buffer (&rest _args))
  (defun persp-make-variable-persp-local (&rest _args))
  (defun persp-kill (&rest _args))
  (defun persp-names ()
    nil)
  (provide 'perspective))

(defvar consult-buffer-sources)

(load-file (expand-file-name "../perspective-project-bridge.el"
                             (file-name-directory
                              (or load-file-name buffer-file-name))))

(ert-deftest perspective-project-bridge-find-perspective-for-buffer-skips-nil-root ()
  "Return nil without creating a perspective when project root is nil."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-persp nil))
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   nil))
                ((symbol-function 'persp-new)
                 (lambda (&rest _args)
                   (ert-fail "persp-new should not be called when project root is nil"))))
        (should-not
         (perspective-project-bridge-find-perspective-for-buffer (current-buffer)))))))

(ert-deftest perspective-project-bridge-find-perspective-for-buffer-creates-perspective ()
  "Create and return a perspective when project root exists."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-persp nil)
        (added-buffer nil))
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'persp-new)
                 (lambda (name)
                   (list :name name)))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'persp-add-buffer)
                 (lambda (buffer)
                   (setq added-buffer buffer))))
        (let ((persp (perspective-project-bridge-find-perspective-for-buffer
                      (current-buffer))))
          (should (equal (plist-get persp :name) "sample-project"))
          (should (eq added-buffer (current-buffer)))
          (should perspective-project-bridge-persp))))))

(ert-deftest perspective-project-bridge-find-file-advice-switches-after-confirmation ()
  "Switch to project perspective for interactive find-file when confirmed."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-confirm-on-interactive-find-file 'prompt)
        (switched-name nil)
        (prompt-count 0)
        (orig-saw-switch nil))
    (with-temp-buffer
      (cl-letf (((symbol-function 'called-interactively-p)
                 (lambda (&rest _args)
                   t))
                ((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (setq prompt-count (1+ prompt-count))
                   t))
                ((symbol-function 'persp-new)
                 (lambda (name)
                   (list :name name)))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'persp-add-buffer)
                 (lambda (&rest _args)))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   'other-persp))
                ((symbol-function 'persp-remove-buffer)
                 (lambda (&rest _args)))
                ((symbol-function 'persp-switch)
                 (lambda (name)
                   (setq switched-name name)))
                ((symbol-function 'persp-switch-to-buffer)
                 (lambda (&rest _args))))
        (perspective-project-bridge-find-file-advice
         (lambda (&rest _args)
           (setq orig-saw-switch (equal switched-name "sample-project"))
           (current-buffer))
         "src/file.el")
        (should (= prompt-count 1))
        (should (equal switched-name "sample-project"))
        (should orig-saw-switch)))))

(ert-deftest perspective-project-bridge-find-file-advice-treats-legacy-true-as-prompt ()
  "Treat legacy boolean true as the `prompt' switch policy."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-confirm-on-interactive-find-file t)
        (prompt-count 0)
        (switch-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'called-interactively-p)
                 (lambda (&rest _args)
                   t))
                ((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (setq prompt-count (1+ prompt-count))
                   nil))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (perspective-project-bridge-find-file-advice
         (lambda (&rest _args)
           (current-buffer))
         "src/file.el")
        (should (= prompt-count 1))
        (should (= switch-count 0))))))

(ert-deftest perspective-project-bridge-find-file-advice-switches-without-prompt-when-policy-always ()
  "Switch perspectives without prompting when policy is `always'."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-confirm-on-interactive-find-file 'always)
        (switched-name nil)
        (orig-saw-switch nil))
    (with-temp-buffer
      (cl-letf (((symbol-function 'called-interactively-p)
                 (lambda (&rest _args)
                   t))
                ((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (ert-fail "Prompt should not run when switch policy is `always'")))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   (list :name "other-project")))
                ((symbol-function 'persp-new)
                 (lambda (name)
                   (list :name name)))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'persp-switch)
                 (lambda (name)
                   (setq switched-name name))))
        (perspective-project-bridge-find-file-advice
         (lambda (&rest _args)
           (setq orig-saw-switch (equal switched-name "sample-project"))
           (current-buffer))
         "src/file.el")
        (should (equal switched-name "sample-project"))
        (should orig-saw-switch)))))

(ert-deftest perspective-project-bridge-find-file-advice-prompts-with-plain-universal-argument-when-policy-always ()
  "Treat `always' like `prompt' when invoked with a plain universal argument."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-confirm-on-interactive-find-file 'always)
        (current-prefix-arg '(4))
        (prompt-count 0)
        (switch-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'called-interactively-p)
                 (lambda (&rest _args)
                   t))
                ((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (setq prompt-count (1+ prompt-count))
                   nil))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (perspective-project-bridge-find-file-advice
         (lambda (&rest _args)
           (current-buffer))
         "src/file.el")
        (should (= prompt-count 1))
        (should (= switch-count 0))))))

(ert-deftest perspective-project-bridge-find-file-advice-keeps-automatic-policy-for-numeric-prefix ()
  "Do not treat numeric prefix arguments like a plain universal argument."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-confirm-on-interactive-find-file 'always)
        (current-prefix-arg 4)
        (switch-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'called-interactively-p)
                 (lambda (&rest _args)
                   t))
                ((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (ert-fail "Prompt should not run for numeric prefixes")))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   (list :name "other-project")))
                ((symbol-function 'persp-new)
                 (lambda (name)
                   (list :name name)))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (perspective-project-bridge-find-file-advice
         (lambda (&rest _args)
           (current-buffer))
         "src/file.el")
        (should (= switch-count 1))))))

(ert-deftest perspective-project-bridge-find-file-advice-skips-switch-when-policy-never ()
  "Keep the current perspective without prompting when policy is `never'."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-confirm-on-interactive-find-file 'never)
        (switch-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'called-interactively-p)
                 (lambda (&rest _args)
                   t))
                ((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (ert-fail "Prompt should not run when switch policy is `never'")))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (perspective-project-bridge-find-file-advice
         (lambda (&rest _args)
           (current-buffer))
         "src/file.el")
        (should (= switch-count 0))))))

(ert-deftest perspective-project-bridge-find-file-advice-skips-prompt-when-already-in-project-perspective ()
  "Skip prompt when current perspective already matches target project."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-confirm-on-interactive-find-file t)
        (prompt-count 0)
        (switch-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'called-interactively-p)
                 (lambda (&rest _args)
                   t))
                ((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (setq prompt-count (1+ prompt-count))
                   t))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   (list :name "sample-project")))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (perspective-project-bridge-find-file-advice
         (lambda (&rest _args)
           (current-buffer))
         "src/file.el")
        (should (= prompt-count 0))
        (should (= switch-count 0))))))

(ert-deftest perspective-project-bridge-find-file-advice-keeps-current-when-declined ()
  "Do not switch perspectives when prompt is declined."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-confirm-on-interactive-find-file t)
        (switch-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'called-interactively-p)
                 (lambda (&rest _args)
                   t))
                ((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   nil))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (perspective-project-bridge-find-file-advice
         (lambda (&rest _args)
           (current-buffer))
         "src/file.el")
        (should (= switch-count 0))))))

(ert-deftest perspective-project-bridge-find-file-advice-skips-for-noninteractive-calls ()
  "Skip prompt and switching for non-interactive find-file calls."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-confirm-on-interactive-find-file t)
        (switch-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'called-interactively-p)
                 (lambda (&rest _args)
                   nil))
                ((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (ert-fail "Prompt should not be shown for non-interactive calls")))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (perspective-project-bridge-find-file-advice
         (lambda (&rest _args)
           (current-buffer))
         "src/file.el")
        (should (= switch-count 0))))))

(ert-deftest perspective-project-bridge-find-file-advice-skips-when-project-root-missing ()
  "Skip prompt and switch when file has no project root."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-confirm-on-interactive-find-file t)
        (perspective-project-bridge-prompt-on-non-project-file nil)
        (switch-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'called-interactively-p)
                 (lambda (&rest _args)
                   t))
                ((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   nil))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (ert-fail "Prompt should not be shown when project root is missing")))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (perspective-project-bridge-find-file-advice
         (lambda (&rest _args)
           (current-buffer))
         "src/file.el")
        (should (= switch-count 0))))))

(ert-deftest perspective-project-bridge-find-file-advice-switches-non-project-file-to-initial-perspective ()
  "Switch to the initial perspective for non-project files when confirmed."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-confirm-on-interactive-find-file 'prompt)
        (perspective-project-bridge-prompt-on-non-project-file t)
        (persp-initial-frame-name "main")
        (switched-name nil)
        (prompt-count 0)
        (orig-saw-switch nil))
    (with-temp-buffer
      (cl-letf (((symbol-function 'called-interactively-p)
                 (lambda (&rest _args)
                   t))
                ((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   nil))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (setq prompt-count (1+ prompt-count))
                   t))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   (list :name "other-perspective")))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'persp-new)
                 (lambda (name)
                   (list :name name)))
                ((symbol-function 'persp-switch)
                 (lambda (name)
                   (setq switched-name name))))
        (perspective-project-bridge-find-file-advice
         (lambda (&rest _args)
           (setq orig-saw-switch (equal switched-name "main"))
           (current-buffer))
         "src/file.el")
        (should (= prompt-count 1))
        (should (equal switched-name "main"))
        (should orig-saw-switch)))))

(ert-deftest perspective-project-bridge-find-file-advice-always-switches-non-project-file-to-initial-perspective ()
  "Switch non-project files without prompting when policy is `always'."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-confirm-on-interactive-find-file 'always)
        (perspective-project-bridge-prompt-on-non-project-file t)
        (persp-initial-frame-name "main")
        (switched-name nil))
    (with-temp-buffer
      (cl-letf (((symbol-function 'called-interactively-p)
                 (lambda (&rest _args)
                   t))
                ((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   nil))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (ert-fail "Prompt should not run when switch policy is `always'")))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   (list :name "other-perspective")))
                ((symbol-function 'persp-new)
                 (lambda (name)
                   (list :name name)))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'persp-switch)
                 (lambda (name)
                   (setq switched-name name))))
        (perspective-project-bridge-find-file-advice
         (lambda (&rest _args)
           (current-buffer))
         "src/file.el")
        (should (equal switched-name "main"))))))

(ert-deftest perspective-project-bridge-find-file-advice-skips-non-project-prompt-when-already-in-initial-perspective ()
  "Skip prompt when a non-project file is opened from the initial perspective."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-confirm-on-interactive-find-file t)
        (perspective-project-bridge-prompt-on-non-project-file t)
        (persp-initial-frame-name "main")
        (prompt-count 0)
        (switch-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'called-interactively-p)
                 (lambda (&rest _args)
                   t))
                ((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   nil))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   (list :name "main")))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (setq prompt-count (1+ prompt-count))
                   t))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (perspective-project-bridge-find-file-advice
         (lambda (&rest _args)
           (current-buffer))
         "src/file.el")
        (should (= prompt-count 0))
        (should (= switch-count 0))))))

(ert-deftest perspective-project-bridge-find-file-advice-respects-reentry-guard ()
  "Bypass prompt and switching when already inside find-file advice."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-confirm-on-interactive-find-file t)
        (perspective-project-bridge--in-find-file-advice t)
        (orig-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'called-interactively-p)
                 (lambda (&rest _args)
                   t))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (ert-fail "Prompt should not run while reentry guard is active"))))
        (perspective-project-bridge-find-file-advice
         (lambda (&rest _args)
           (setq orig-count (1+ orig-count))
           (current-buffer))
         "src/file.el")
        (should (= orig-count 1))))))

(ert-deftest perspective-project-bridge-consult-file-action-switches-after-confirmation ()
  "Switch to project perspective for consult file actions when confirmed."
  (let* ((perspective-project-bridge-mode t)
        (perspective-project-bridge-consult-prompt-on-file-action 'prompt)
        (switched-name nil)
        (prompt-count 0)
        (orig-saw-switch nil)
        (perspective-project-bridge--consult-file-action-function
         (lambda (&rest _args)
           (setq orig-saw-switch (equal switched-name "sample-project"))
           'ok))
         )
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (setq prompt-count (1+ prompt-count))
                   t))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   (list :name "other-project")))
                ((symbol-function 'persp-new)
                 (lambda (name)
                   (list :name name)))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'persp-switch)
                 (lambda (name)
                   (setq switched-name name))))
        (perspective-project-bridge--consult-file-action "src/file.el")
        (should (= prompt-count 1))
        (should (equal switched-name "sample-project"))
        (should orig-saw-switch)))))

(ert-deftest perspective-project-bridge-consult-file-action-switches-without-prompt-when-policy-always ()
  "Switch perspectives without prompting when consult policy is `always'."
  (let* ((perspective-project-bridge-mode t)
        (perspective-project-bridge-consult-prompt-on-file-action 'always)
        (switched-name nil)
        (orig-saw-switch nil)
        (perspective-project-bridge--consult-file-action-function
         (lambda (&rest _args)
           (setq orig-saw-switch (equal switched-name "sample-project"))
           'ok))
         )
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (ert-fail "Prompt should not run when switch policy is `always'")))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   (list :name "other-project")))
                ((symbol-function 'persp-new)
                 (lambda (name)
                   (list :name name)))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'persp-switch)
                 (lambda (name)
                   (setq switched-name name))))
        (perspective-project-bridge--consult-file-action "src/file.el")
        (should (equal switched-name "sample-project"))
        (should orig-saw-switch)))))

(ert-deftest perspective-project-bridge-consult-file-action-prompts-with-override ()
  "Treat consult file `always' policy like `prompt' when override is active."
  (let* ((perspective-project-bridge-mode t)
         (perspective-project-bridge-consult-prompt-on-file-action 'always)
         (perspective-project-bridge--consult-prompt-override t)
         (prompt-count 0)
         (switch-count 0)
         (perspective-project-bridge--consult-file-action-function
          (lambda (&rest _args)
            'ok)))
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (setq prompt-count (1+ prompt-count))
                   nil))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (perspective-project-bridge--consult-file-action "src/file.el")
        (should (= prompt-count 1))
        (should (= switch-count 0))))))

(ert-deftest perspective-project-bridge-consult-file-action-skips-switch-when-policy-never ()
  "Keep the current perspective without prompting when consult policy is `never'."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-consult-prompt-on-file-action 'never)
        (perspective-project-bridge--consult-file-action-function
         (lambda (&rest _args)
           'ok))
        (switch-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (ert-fail "Prompt should not run when switch policy is `never'")))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (perspective-project-bridge--consult-file-action "src/file.el")
        (should (= switch-count 0))))))

(ert-deftest perspective-project-bridge-consult-file-action-keeps-current-when-declined ()
  "Do not switch perspectives for consult file actions when prompt is declined."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-consult-prompt-on-file-action t)
        (perspective-project-bridge--consult-file-action-function
         (lambda (&rest _args)
           'ok))
        (prompt-count 0)
        (switch-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (setq prompt-count (1+ prompt-count))
                   nil))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   (list :name "other-project")))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (perspective-project-bridge--consult-file-action "src/file.el")
        (should (= prompt-count 1))
        (should (= switch-count 0))))))

(ert-deftest perspective-project-bridge-consult-file-action-switches-non-project-file-to-initial-perspective ()
  "Switch to the initial perspective for consult non-project file actions."
  (let* ((perspective-project-bridge-mode t)
         (perspective-project-bridge-consult-prompt-on-file-action t)
         (perspective-project-bridge-prompt-on-non-project-file t)
         (persp-initial-frame-name "main")
         (switched-name nil)
         (prompt-count 0)
         (orig-saw-switch nil)
         (perspective-project-bridge--consult-file-action-function
          (lambda (&rest _args)
            (setq orig-saw-switch (equal switched-name "main"))
            'ok))
         )
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   nil))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (setq prompt-count (1+ prompt-count))
                   t))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   (list :name "other-project")))
                ((symbol-function 'persp-new)
                 (lambda (name)
                   (list :name name)))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'persp-switch)
                 (lambda (name)
                   (setq switched-name name))))
        (perspective-project-bridge--consult-file-action "src/file.el")
        (should (= prompt-count 1))
        (should (equal switched-name "main"))
        (should orig-saw-switch)))))

(ert-deftest perspective-project-bridge-consult-file-action-skips-non-project-prompt-when-already-in-initial-perspective ()
  "Skip non-project prompt for consult file action in the initial perspective."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-consult-prompt-on-file-action t)
        (perspective-project-bridge-prompt-on-non-project-file t)
        (persp-initial-frame-name "main")
        (perspective-project-bridge--consult-file-action-function
         (lambda (&rest _args)
           'ok))
        (prompt-count 0)
        (switch-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   nil))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   (list :name "main")))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (setq prompt-count (1+ prompt-count))
                   t))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (perspective-project-bridge--consult-file-action "src/file.el")
        (should (= prompt-count 0))
        (should (= switch-count 0))))))

(ert-deftest perspective-project-bridge-consult-file-action-skips-when-already-in-target ()
  "Do not prompt for consult file actions when already in target perspective."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-consult-prompt-on-file-action t)
        (perspective-project-bridge--consult-file-action-function
         (lambda (&rest _args)
           'ok))
        (prompt-count 0)
        (switch-count 0))
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   (list :name "sample-project")))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (setq prompt-count (1+ prompt-count))
                   t))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (perspective-project-bridge--consult-file-action "src/file.el")
        (should (= prompt-count 0))
        (should (= switch-count 0))))))

(ert-deftest perspective-project-bridge-consult-file-action-skips-when-root-missing ()
  "Do not prompt for consult file actions when project root is unavailable."
  (let ((perspective-project-bridge-mode t)
        (perspective-project-bridge-consult-prompt-on-file-action t)
        (perspective-project-bridge--consult-file-action-function
         (lambda (&rest _args)
           'ok))
        (perspective-project-bridge-prompt-on-non-project-file nil))
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   nil))
                ((symbol-function 'y-or-n-p)
                 (lambda (&rest _args)
                   (ert-fail "Prompt should not run when project root is unavailable"))))
        (perspective-project-bridge--consult-file-action "src/file.el")))))

(ert-deftest perspective-project-bridge-consult-buffer-target-prefers-project ()
  "Prefer project perspective names over other perspective membership."
  (let ((perspective-project-bridge-mode t))
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'persp-buffer-in-other-p)
                 (lambda (_buffer)
                   (cons (selected-frame) "other-perspective"))))
        (should (equal (perspective-project-bridge--consult-buffer-target-for-buffer
                        (current-buffer))
                       '(:name "sample-project" :kind project)))))))

(ert-deftest perspective-project-bridge-normalize-consult-buffer-switch-policy-treats-query-as-prompt ()
  "Treat legacy `query' as `prompt' for consult buffer policy."
  (should (eq (perspective-project-bridge--normalize-consult-buffer-switch-policy 'query)
              'prompt)))

(ert-deftest perspective-project-bridge-consult-buffer-open-buffer-switches-project-buffer ()
  "Switch to the project perspective when consult buffer policy is `always'."
  (let* ((perspective-project-bridge-mode t)
         (perspective-project-bridge-consult-buffer-switch-policy 'always)
         (switched-name nil)
         (orig-saw-switch nil)
         (perspective-project-bridge--consult-buffer-action-function
          (lambda (&rest _args)
            (setq orig-saw-switch (equal switched-name "sample-project"))
            'ok))
         )
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   'mock-project))
                ((symbol-function 'project-root)
                 (lambda (_project)
                   "/tmp/sample-project/"))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   (list :name "other-project")))
                ((symbol-function 'persp-new)
                 (lambda (name)
                   (list :name name)))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'persp-switch)
                 (lambda (name)
                   (setq switched-name name))))
        (rename-buffer "sample-buffer" t)
        (perspective-project-bridge--consult-buffer-open-buffer (current-buffer))
        (should (equal switched-name "sample-project"))
        (should orig-saw-switch)))))

(ert-deftest perspective-project-bridge-consult-buffer-open-buffer-moves-when-policy-never ()
  "Move the selected buffer into the current perspective when policy is `never'."
  (let* ((perspective-project-bridge-mode t)
         (perspective-project-bridge-consult-buffer-switch-policy 'never)
         (moved-buffer nil)
         (action-called nil)
         (perspective-project-bridge--consult-buffer-action-function
          (lambda (&rest _args)
            (setq action-called t)
            'ok))
         )
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   nil))
                ((symbol-function 'persp-buffer-in-other-p)
                 (lambda (_buffer)
                   (cons (selected-frame) "other-perspective")))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   (list :name "current-perspective")))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'persp-set-buffer)
                 (lambda (buffer)
                   (setq moved-buffer buffer))))
        (rename-buffer "sample-buffer" t)
        (perspective-project-bridge--consult-buffer-open-buffer (current-buffer))
        (should (eq moved-buffer (current-buffer)))
        (should action-called)))))

(ert-deftest perspective-project-bridge-consult-buffer-open-buffer-cancels-prompt ()
  "Do not open or move the buffer when consult prompt is cancelled."
  (let* ((perspective-project-bridge-mode t)
         (perspective-project-bridge-consult-buffer-switch-policy 'prompt)
         (action-called nil)
         (move-count 0)
         (switch-count 0)
         (perspective-project-bridge--consult-buffer-action-function
          (lambda (&rest _args)
            (setq action-called t)
            'ok))
         )
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   nil))
                ((symbol-function 'persp-buffer-in-other-p)
                 (lambda (_buffer)
                   (cons (selected-frame) "other-perspective")))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   (list :name "current-perspective")))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'read-multiple-choice)
                 (lambda (&rest _args)
                   '(?c "cancel" "Abort opening this candidate")))
                ((symbol-function 'persp-set-buffer)
                 (lambda (&rest _args)
                   (setq move-count (1+ move-count))))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (rename-buffer "sample-buffer" t)
        (perspective-project-bridge--consult-buffer-open-buffer (current-buffer))
        (should-not action-called)
        (should (= move-count 0))
        (should (= switch-count 0))))))

(ert-deftest perspective-project-bridge-consult-buffer-open-buffer-prompts-with-override ()
  "Treat consult buffer `never' policy like `prompt' when override is active."
  (let* ((perspective-project-bridge-mode t)
         (perspective-project-bridge-consult-buffer-switch-policy 'never)
         (perspective-project-bridge--consult-prompt-override t)
         (action-called nil)
         (move-count 0)
         (switch-count 0)
         (perspective-project-bridge--consult-buffer-action-function
          (lambda (&rest _args)
            (setq action-called t)
            'ok)))
    (with-temp-buffer
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _args)
                   nil))
                ((symbol-function 'persp-buffer-in-other-p)
                 (lambda (_buffer)
                   (cons (selected-frame) "other-perspective")))
                ((symbol-function 'persp-curr)
                 (lambda ()
                   (list :name "current-perspective")))
                ((symbol-function 'persp-name)
                 (lambda (persp)
                   (plist-get persp :name)))
                ((symbol-function 'read-multiple-choice)
                 (lambda (&rest _args)
                   '(?c "cancel" "Abort opening this candidate")))
                ((symbol-function 'persp-set-buffer)
                 (lambda (&rest _args)
                   (setq move-count (1+ move-count))))
                ((symbol-function 'persp-switch)
                 (lambda (&rest _args)
                   (setq switch-count (1+ switch-count)))))
        (rename-buffer "sample-buffer" t)
        (perspective-project-bridge--consult-buffer-open-buffer (current-buffer))
        (should-not action-called)
        (should (= move-count 0))
        (should (= switch-count 0))))))

(ert-deftest consult-buffer-with-project-perspective-transforms-buffer-sources ()
  "Rewrite consult buffer sources without touching file preview state."
  (let ((perspective-project-bridge-mode t)
        (persp-mode t)
        (consult-buffer-sources
         (list '(:name "Buffers" :category buffer :state buffer-state)
               '(:name "Files" :category file :state file-state)))
        (orig-file-action (lambda (&rest _args) 'file))
        (orig-buffer-action (lambda (&rest _args) 'buffer))
        (saw-buffer-source nil)
        (saw-file-source nil)
        (file-action-overridden nil))
    (cl-letf (((symbol-function 'consult--file-action)
               orig-file-action)
              ((symbol-function 'consult--buffer-action)
               orig-buffer-action)
              ((symbol-function 'consult-buffer)
               (lambda ()
                 (setq saw-buffer-source (car consult-buffer-sources))
                 (setq saw-file-source (cadr consult-buffer-sources))
                 (setq file-action-overridden
                       (not (eq (symbol-function 'consult--file-action)
                                orig-file-action)))
                 'ok)))
      (should (eq (consult-buffer-with-project-perspective) 'ok))
      (should (null (plist-get saw-buffer-source :state)))
      (should (eq (plist-get saw-buffer-source :action)
                  #'perspective-project-bridge--consult-buffer-open-buffer))
      (should (eq (plist-get saw-file-source :state) 'file-state))
      (should file-action-overridden))))

(ert-deftest consult-buffer-with-project-perspective-captures-plain-universal-argument ()
  "Capture plain universal arguments for one-shot consult prompt overrides."
  (let ((perspective-project-bridge-mode t)
        (persp-mode t)
        (consult-buffer-sources nil)
        (current-prefix-arg '(4)))
    (cl-letf (((symbol-function 'consult--buffer-action)
               (lambda (&rest _args) 'buffer))
              ((symbol-function 'consult--file-action)
               (lambda (&rest _args) 'file))
              ((symbol-function 'consult-buffer)
               (lambda ()
                 perspective-project-bridge--consult-prompt-override)))
      (should (consult-buffer-with-project-perspective)))))

(provide 'perspective-project-bridge-test)

;;; perspective-project-bridge-test.el ends here
